### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by carrotflakes** [carrotflakes/enustik#1]
- [ ] pianoroll
  - [ ] rectangle selection
  - [ ] duration unit selection
  - [ ] move, cut, copy, paste notes
  - [ ] sound preview
  - [ ] time indicator
- [ ] multi channels
- [ ] persistence
  - [ ] SMF
  - [ ] localstorage
- [ ] backend
  - [ ] fcmml
  - [ ] Web MIDI API
